// Gerardo Cadagan

/*This is a program that calculates the gains/losses generated by a stock investment
after buying and selling shares on the stock market through the iTrade online
broker platform */

//Header files
#include <iostream>
using namespace std;

int main()
{
    //Title
    cout << "Stock Investment Performance Calculator ..." << endl;
    cout << endl;

    //variables
    string company_Name, symbol;
    int number_Of_Shares;
    double cost_Buy_Share, cost_Sell_Share;

    // ask for user inputs
    cout << "Company Name (no spaces) & symbol:          ";
    cin >> company_Name; cin >> symbol;
   

    cout << "Number of Shares transacted:                ";
    cin >> number_Of_Shares;
  

    cout << "Cost per Share (@ buying):                  ";
    cin >> cost_Buy_Share;

    cout << "Price per Share (@ selling):                ";
    cin >> cost_Sell_Share;
    cout << endl;


// title of new display showing calculations of inputs

    cout << "Realized Gains/Losses Report ..." << endl;

    cout << "-------------------------------------" << endl;

// display stock purchased and amount to user for report

    cout << "Stock:           "; cout << company_Name << " (" << symbol << ")";
    cout << endl;
    cout << "Quantity:        "; cout << number_Of_Shares << " Shares.";
    cout << endl;
    cout << endl;

// define variables and perform calculations and display to user report 


    const double percentage_Rate = 0.02;

    double total_Cost = (percentage_Rate * cost_Buy_Share * number_Of_Shares) + (cost_Buy_Share * number_Of_Shares);

    double total_Proceeds = (number_Of_Shares * cost_Sell_Share) - (percentage_Rate * cost_Sell_Share * number_Of_Shares);

    double percentage_Gain_Loss = (total_Proceeds - total_Cost) / total_Cost * 100;

    cout << "Total Cost:      " << "$" << (percentage_Rate * cost_Buy_Share * number_Of_Shares) + (cost_Buy_Share * number_Of_Shares);
    cout << endl;
    cout << "Total Proceeds:  " << "$" << (number_Of_Shares * cost_Sell_Share) - (percentage_Rate * cost_Sell_Share * number_Of_Shares);
    cout << endl;
    cout << "Commissions:     " << "$" << (percentage_Rate * cost_Sell_Share * number_Of_Shares) + (number_Of_Shares * cost_Buy_Share * percentage_Rate);
    cout << endl; 
    cout << "Gains/Losses:    " << "$" << (total_Proceeds - total_Cost) << " (" << percentage_Gain_Loss << "%)";
    cout << endl; 


    return 0;





}
